### ISSUE TITLE
v1.8.0 - Exit button redirects me to options button

### ISSUE THREAD

**Issue by Raoul1808** [lilybeevee/bab-be-u#100]
Platform: Windows 10

Build: v1.8.0 (win-64 package with love included)

Issue: Mouse gets redirected to Options button when it hovers the Exit button

Steps to reproduce: Go to main menu, put the mouse on the Exit button.

**Comment by jillstingray** [comment]
releases are old af clone or download instead its already fixed

**Comment by oatmealine** [comment]
was this ever a bug though?? i added it intentially as a way to say "you cannot escape" but im p sure it was removed later

**Comment by jillstingray** [comment]
ye and u left it there for 5 years its annoying u doofus
