### ISSUE TITLE
Rotatable Text Does Not Work As Expected

### ISSUE THREAD

**Issue by HyperBeast43** [lilybeevee/bab-be-u#111]
If you spell "roc be keek" and have it face up (as in roc on bottom) keek becomes a roc instead of the other way around.

**Comment by Adrthegamedev** [comment]
That's intended, you're spelling "Keek be roc" vertically.
it's like making "Roc be keek" rotated normally, but then inversing it. You get "Keek be roc".

**Comment by vitellaryjr** [comment]
yeah this is how text is parsed, rules are only read right, downright and down. no issue here, everything working as intended
