### ISSUE TITLE
Sort of like f4 in normal BiY

### ISSUE THREAD

**Issue by JustAGenericUsername** [lilybeevee/bab-be-u#139]
So in normal BiY, if you press f4 you can type something and then it lets you put that rule somewhere in the level. Something similar to that would be nice, as it is a pain to have to find each word and put them down individually. If it were to be implemented, it would hopefully work for normal words and the bab equivalent both.

**Comment by notMEEPoffaith** [comment]
it's in the releases just type out something in the object selector
not sure about current github version(not release) doe, i haven't gotten it yet
