### ISSUE TITLE
bab be u performance analysis

### ISSUE THREAD

**Issue by Patashu** [lilybeevee/bab-be-u#9]
Finishing a turn is starting to feel very sluggish. I did some profiling to see what the offenders are.

I opened up Kaleidoscope and added a lot of code to doMovement like

    end_time = love.timer.getTime();
    print("fallBlock() took: "..tostring(round((end_time-start_time)*1000)).."ms")
    start_time = end_time

And a typical turn looks like this:

[---- begin turn ----]
move: 0, -1
doMovement() took: 3ms
-- begin parse --
parseRules() took: 11ms
fallBlock() took: 0ms
updateUnits() took: 14ms
-- begin parse --
parseRules() took: 11ms
convertUnits() took: 1ms
updateUnits() took: 12ms
-- begin parse --
parseRules() took: 12ms

So in total we're spending ~30ms on parseRules and ~26ms on updateUnits. Ideally, we would like to get this number down below ~16ms, so we would like a 3x performance speedup or better.

We can start with a VERY easy one: parseRules is very slow, so only run it if there's any possibility rules changed since the last time we ran it (a text object was created, destroyed or moved, or a WORD rule exists, or a topology-altering rule exists).

Then we have a second very easy one: updateUnits() is only slow because of ONE part:

-- begin parse --
initial deletions took: 0ms
up to creat took: 0ms
up to os stuff took: 13ms
final checks took: 0ms
-- begin parse --

Specifically, the loop that starts here is extremely slow:

https://github.com/lilybeevee/bab-be-u/blob/master/game/unit.lua#L505

It does many things that can be optimized away, for example it calls hasProperty once per unit for many different properties, but if we want to iterate over units that have a property, the smart way to do that is  getUnitsWithEffect.

We also don't need to iterate over all units to check if any of them are bab/keek/meem/os. You can just iterate units_by_name or check matchesRule("keek", "be", "u") or whatever.

**Comment by Patashu** [comment]
I did all the low hanging fruit.

**Comment by Patashu** [comment]
Done even more perf. Now the ENTIRE GAMEPLAY LOGIC COMBINED in Kaleidoscope is 4ms on average. scene.draw(), however, is 10ms on average, and when parseRules() does run, it's 15ms on average, so these two places would be the next things to focus on, in addition to input latency reduction and particle effect optimization.

**Comment by Patashu** [comment]
I also improved input latency a lot, which helps a lot with the feeling of snappiness on its own.

**Comment by cynaba** [comment]
![hk416 yay](https://user-images.githubusercontent.com/20518363/59336746-b6b8f780-8d31-11e9-801f-5feb9101c96d.gif)

**Comment by Patashu** [comment]
After further investigation, it seems particle effects are the #1 laggiest thing in bab by a long shot right now.

**Comment by Patashu** [comment]
Imma just close this since perf is in a pretty good place right now \o/
