### ISSUE TITLE
Autoupdates.

### ISSUE THREAD

**Issue by TheGLander** [lilybeevee/bab-be-u#99]

**Comment by jillstingray** [comment]
what

**Comment by TheGLander** [comment]
Make the game automatically update

**Comment by jillstingray** [comment]
why

**Comment by danielbup** [comment]
I dont think you can do that

**Comment by danielbup** [comment]
I dont think you can make something automatically update on github sorry

**Comment by TheGLander** [comment]
Uh..You can
1. On game start, fetch stable releases
2. If there are any, download them and copy to the game directory

**Comment by danielbup** [comment]
🤔

**Comment by lilybeevee** [comment]
autoupdates are too complicated and very unnecessary for bab, the reason it gets so many updates is because it's unfinished - updating manually is not a big hassle with git

**Comment by oatmealine** [comment]
running `git fetch` and `git pull` isnt as easy as just, well, running it, cus you have to also account for if the user doesnt have git installed, or the game didnt come with a git folder
ill try to come up with a quick bodge though

**Comment by oatmealine** [comment]
commit 662689d00b605db3e4b57994c872bbfc13647a0b should hopefully add autoupdate, however its highly experimental and will only work if git is in path and the game is ran with a folder, not a .love file
